services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
      target: development
    ports:
      - '4200:4200'
    volumes:
      - ./client:/app/client
      - ./shared:/app/shared
      - /app/client/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      target: development
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app/server
      - ./shared:/app/shared
      - /app/server/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_dev:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmin

volumes:
  mongodb_data_dev:
